version: '2'

services:
  scraper:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./build/images:/app/build/images
  viewer:
    build:
      context: ./site/
      dockerfile: Dockerfile
    command: bundle exec jekyll serve --incremental --watch --force_polling -H 0.0.0.0 -P 8000
    volumes:
      - ./site:/site
      - ./build/images:/site/photos
      - bundlercache-site:/bundlercache
    ports:
      - '8000:8000'
  docs:
    build:
      context: ./docs/
      dockerfile: Dockerfile
    volumes:
      - ./docs:/site
      - bundlercache-docs:/bundlercache
    ports:
      - '8080:8080'
      - '35729:35729'
volumes:
  bundlercache-site:
  bundlercache-docs: