version: '2'

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/site
      - ../build/images:/site/photos
      - bundlervol:/box
    ports:
      - '8000:4000'
volumes:
  bundlervol:
