name: Java CI
on: [push]
jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: dos2unix gradlew
      - run: chmod +x gradlew
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew assemble
  test:
    needs: assemble
    runs-on: ubuntu-latest
    steps:
      - run: chmod +x gradlew
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Execute unit tests
        run: ./gradlew test